const nodemailer = require('nodemailer');

// For testing, we'll use Ethereal (fake SMTP)
// In production, use SendGrid, AWS SES, or your own SMTP

async function createTransporter() {
    // Use Ethereal for testing (no real email sent)
    const testAccount = await nodemailer.createTestAccount();
    
    return nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
            user: testAccount.user,
            pass: testAccount.pass
        }
    });
}

async function sendActionItemReminder(email, actionItem, meetingTitle) {
    try {
        const transporter = await createTransporter();
        
        const mailOptions = {
            from: '"AI Meeting Assistant" <noreply@meetingassistant.com>',
            to: email,
            subject: `⏰ Action Item Reminder: ${actionItem.description}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                    <h2 style="color: #4a90d9;">📋 Action Item Reminder</h2>
                    <p>Hello,</p>
                    <p>This is a reminder about your action item from the meeting:</p>
                    
                    <div style="background: #f5f7fa; padding: 15px; border-radius: 8px; margin: 15px 0;">
                        <h3 style="margin: 0 0 8px 0; color: #2d3748;">${meetingTitle}</h3>
                        <p style="margin: 0; color: #4a5568;"><strong>Task:</strong> ${actionItem.description}</p>
                        <p style="margin: 0; color: #4a5568;"><strong>Status:</strong> ${actionItem.status}</p>
                    </div>
                    
                    <p style="color: #718096; font-size: 14px;">
                        Please complete this task as soon as possible.
                    </p>
                    
                    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
                    <p style="color: #a0aec0; font-size: 12px; text-align: center;">
                        Generated by AI Meeting Assistant
                    </p>
                </div>
            `
        };

        const info = await transporter.sendMail(mailOptions);
        console.log('📧 Email sent:', info.messageId);
        console.log('🔗 Preview URL:', nodemailer.getTestMessageUrl(info));
        
        return info;
    } catch (error) {
        console.error('Email error:', error);
        throw error;
    }
}

module.exports = { sendActionItemReminder };
